config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: { invitations: 'users/invitations' }
  root 'items#index'
  resources :items do
    collection do
      get :active
      get :inactive
      get :borrowed
      get :on_place
    end
    member do
      post :request_rent
      post :return_item
    end
  end

  resources :friends, only: %i[index show] do
    member do
      get :items
      get :chat
    end
  end
  resources :invitations, only: %i[create] do
    member do
      post :accept
      post :reject
    end
  end

  resources :notifications, only: %i[index] do
    collection do
      get :all
    end
    member do
      post :mark_as_read
    end
  end

  resources :rental_requests, only: %i[] do
    member do
      post :accept
      post :reject
    end
  end

  resource :messages, only: %i[create]
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!
  def index
    @received_invitations = current_user.received_invitations.not_processed
    @sent_invitations = current_user.sent_invitations
    @friends = current_user.friends
  end

  def show
    friend
    redirect_to action: :items
  end

  def items
    friend
  end

  def chat
    @messages = Message.between(current_user, friend)
    @message = Message.new(receipient_id: friend.id, sender_id: current_user.id)
  end

  private

  def friend
    @friend ||= current_user.friends.find(params[:id])
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_friend.html.erb
<div class="card mt-4">
  <div class="card-body">
    <h5 class="card-title">
      <%= friend.email %>
    </h5>
    <%= link_to 'Items', items_friend_path(friend), class: 'card-link' %>
    <%= link_to 'Chat', chat_friend_path(friend), class: 'card-link' %>
  </div>
</div>

app/views/friends/chat.html.erb
<%= render 'friends/friend', friend: @friend %>
<section style="background-color: #eee;">
  <div class="container py-5">

    <div class="row d-flex justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-6">

        <div class="card" id="chat2">
          <div class="card-header d-flex justify-content-between align-items-center p-3">
            <h5 class="mb-0">Chat</h5>
          </div>
          <div class="card-body" id="messages" data-mdb-perfect-scrollbar="true" style="position: relative; height: 400px; overflow-y: scroll;">

            <%= turbo_stream_from [current_user, :messages] %>
            <% @messages.each do |message| %>
              <%= render 'messages/message', message: message, current_user: current_user %>
            <% end %>

          </div>
          <div class="card-footer text-muted d-flex justify-content-start align-items-center p-3">
            <%= render 'messages/form', message: @message %>
          </div>
        </div>

      </div>
    </div>

  </div>
</section>

app/views/friends/index.html.erb
<h1>
  Friends
</h1>
<%= button_tag 'Invite friend', class: 'btn btn-primary', data: { bs_toggle: 'modal', bs_target: '#exampleModal' } %>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          Invite friend
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with model: Invitation.new do |form| %>
        <div class="modal-body">
          <div class="form-group">
            <%= form.label :email, class: 'form-label' %>
            <%= form.text_field :email, class: 'form-control form-control-lg', placeholder: 'Email' %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= form.submit 'Send invitation', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render 'invitations/invitations', received_invitations: @received_invitations, sent_invitations: @sent_invitations %>

<% @friends.each do |friend| %>
  <%= render 'friends/friend', friend: friend %>
<% end %>

app/views/friends/items.html.erb
<%= render 'friends/friend', friend: @friend %>
<h1>Items</h1>
<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @friend.items.each do |item| %>
    <tr>
      <td><%= item.name %></td>
      <td>
        <% if item.requested_by?(current_user) %>
        <span class="text-muted">
          Request pending
        </span>
        <% else %>
          <%= link_to 'Borrow', request_rent_item_path(item), data: { turbo_method: :post } %>
        <% end %>
        </tr>
  <% end %>
  </tbody>
</table>

app/views/friends/show.html.erb
<h1>Friends#show</h1>
<p>Find me in app/views/friends/show.html.erb</p>