config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: { invitations: 'users/invitations' }
  root 'items#index'
  resources :items do
    collection do
      get :active
      get :inactive
      get :borrowed
      get :on_place
    end
    member do
      post :request_rent
      post :return_item
    end
  end

  resources :friends, only: %i[index show] do
    member do
      get :items
      get :chat
    end
  end
  resources :invitations, only: %i[create] do
    member do
      post :accept
      post :reject
    end
  end

  resources :notifications, only: %i[index] do
    collection do
      get :all
    end
    member do
      post :mark_as_read
    end
  end

  resources :rental_requests, only: %i[] do
    member do
      post :accept
      post :reject
    end
  end

  resource :messages, only: %i[create]
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id         :bigint           not null, primary key
#  data       :json
#  read_at    :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_notifications_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Notification < ApplicationRecord
  include ActionView::RecordIdentifier
  belongs_to :user

  after_create_commit do
    broadcast_append_to [user, :notifications], target: 'notifications_list', partial: 'notifications/notification', locals: { notification: self }
    broadcast_replace_to [user, :notifications], target: dom_id(user, :notifications_badge), partial: 'notifications/notifications_badge', locals: { user: user }
  end

  scope :unread, -> { where(read_at: nil) }

  def unread?
    read_at.nil?
  end
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

class NotificationsController < ApplicationController

  def index
    @notifications = current_user.notifications.unread
  end

  def all
    @notifications = current_user.notifications
  end

  def mark_as_read
    @notification = Notification.find(params[:id])
    @notification.update(read_at: Time.now)
    redirect_to notifications_path
  end
end

app/views/notifications/_notification.html.erb
<div class="d-flex justify-content-between">
  <p class="<%= notification.unread? && 'fw-bold' %>">
    <%= notification.user.email %>
  </p>
  <%= link_to notification.data&.fetch('path', notifications_path) do %>
    <p class="<%= notification.unread? && 'fw-bold' %>">
      <%= notification.data&.fetch('message', '') %>
    </p>
  <% end %>
  <div class="d-flex flex-row gap-2">
    <% if notification.unread? %>
      <%= link_to 'Mark as Read', mark_as_read_notification_path(notification), class: 'btn btn-light min-width-btn', data: { turbo_method: :post } %>
    <% end %>

  </div>
</div>

app/views/notifications/_notifications_badge.html.erb
<%= turbo_frame_tag dom_id(user, :notifications_badge) do %>
  <% if user.notifications.count.positive? %>
    <span class="badge rounded-pill bg-danger">
                <%= user.notifications.unread.count %>
              </span>
  <% end %>
<% end %>

app/views/notifications/_notifications_list.html.erb
<div id="notifications_list" class="d-flex flex-column gap-2">
  <% notifications.each do |notification| %>
    <%= render notification %>
  <% end %>
</div>

app/views/notifications/all.html.erb
<div class="container-fluid">
  <h1>All notifications</h1>
  <%= link_to 'All', all_notifications_path %>
  <%= render 'notifications/notifications_list', notifications: @notifications %>
</div>

app/views/notifications/index.html.erb
<div class="container-fluid">
  <h1>Notification</h1>
  <div id="notifications_list">
    <% @notifications.each do |notification| %>
      <%= render notification %>
    <% end %>
  </div>
</div>