config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: { invitations: 'users/invitations' }
  root 'items#index'
  resources :items do
    collection do
      get :active
      get :inactive
      get :borrowed
      get :on_place
    end
    member do
      post :request_rent
      post :return_item
    end
  end

  resources :friends, only: %i[index show] do
    member do
      get :items
      get :chat
    end
  end
  resources :invitations, only: %i[create] do
    member do
      post :accept
      post :reject
    end
  end

  resources :notifications, only: %i[index] do
    collection do
      get :all
    end
    member do
      post :mark_as_read
    end
  end

  resources :rental_requests, only: %i[] do
    member do
      post :accept
      post :reject
    end
  end

  resource :messages, only: %i[create]
end

app/views/shared/_nav_link.html.erb
<%= link_to label, path, class: nav_link_class(path) %>

app/views/shared/_navbar.html.erb
<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
  <p class="mb-0 text-primary">
    <%= current_user.email %>
  </p>
  <div class="navbar-nav">
    <%= render 'shared/nav_link', label: 'All', path: root_path %>
    <%= render 'shared/nav_link', label: 'Active', path: active_items_path %>
    <%= render 'shared/nav_link', label: 'Inactive', path: inactive_items_path %>
    <%= render 'shared/nav_link', label: 'Borrowed', path: borrowed_items_path %>
    <%= render 'shared/nav_link', label: 'On place', path: on_place_items_path %>
    <%= render 'shared/nav_link', label: 'Friends', path: friends_path %>
    <%= link_to notifications_path, class: nav_link_class(notifications_path) do %>
      <span>Notifications</span>
      <%= render 'notifications/notifications_badge', user: current_user %>
    <% end %>
    <li class="nav-item">
      <%= link_to 'Log out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' %>
    </li>
  </div>
</div>