config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: { invitations: 'users/invitations' }
  root 'items#index'
  resources :items do
    collection do
      get :active
      get :inactive
      get :borrowed
      get :on_place
    end
    member do
      post :request_rent
      post :return_item
    end
  end

  resources :friends, only: %i[index show] do
    member do
      get :items
      get :chat
    end
  end
  resources :invitations, only: %i[create] do
    member do
      post :accept
      post :reject
    end
  end

  resources :notifications, only: %i[index] do
    collection do
      get :all
    end
    member do
      post :mark_as_read
    end
  end

  resources :rental_requests, only: %i[] do
    member do
      post :accept
      post :reject
    end
  end

  resource :messages, only: %i[create]
end

app/models/item.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: items
#
#  id             :bigint           not null, primary key
#  active         :boolean
#  borrowed       :boolean
#  borrowed_at    :datetime
#  item_type      :integer          default("other"), not null
#  name           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  borrowed_to_id :integer
#  user_id        :integer
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Item < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }

  enum item_type: { book: 0, cd: 1, electric_device: 2, flower: 3, other: 4 }
  validates :item_type, inclusion: { in: item_types.keys }

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :borrowed, -> { where(borrowed: true) }
  scope :on_place, -> { where(borrowed: false) }

  belongs_to :user, optional: true
  belongs_to :borrowed_to, class_name: 'User', optional: true, foreign_key: 'borrowed_to_id'
  has_many :rental_requests, dependent: :destroy

  def requested_by?(requesting_user)
    rental_requests.where(user_id: requesting_user.id).exists?
  end

  def requested?
    rental_requests.exists?
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /items or /items.json
  def index
    @items = current_user.items
  end

  # GET /items/1 or /items/1.json
  def show; end

  # GET /items/new
  def new
    @item = current_user.items.build
  end

  # GET /items/1/edit
  def edit; end

  # POST /items or /items.json
  def create
    @item = current_user.items.new(item_params)
    respond_to do |format|
      if @item.save!
        format.html { redirect_to item_url(@item), notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def active
    @items = current_user.items.active
  end

  def inactive
    @items = current_user.items.inactive
  end

  def borrowed
    @items = current_user.items.borrowed
  end

  def on_place
    @items = current_user.items.on_place
  end

  def request_rent
    item = Item.find(params[:id])
    item.rental_requests.create!(user: current_user)
    owner = item.user
    notification_data = {
      message: "User #{current_user.email} requested to rent your item #{item.name}",
      type: 'rental_request',
      path: item_path(item)
    }
    NotificationsJob.perform_later(owner.id, notification_data)
    RentalRequestJob.perform_later(owner.id, current_user.id, item.id)
    redirect_to items_friend_path(owner)
  end

  def return_item
    item = current_user.items.find(params[:id])
    item.update(borrowed: false, borrowed_at: nil, borrowed_to_id: nil)
    redirect_to items_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = current_user.items.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:name, :active, :borrowed, :item_type)
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
  def nav_link_class(path)
    ['nav-link', ('active' if current_page?(path))]
  end
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block", class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-check">
    <%= form.label :active, class: 'form-check-label' %>
    <%= form.check_box :active, class: 'form-check-input' %>
  </div>

  <div class="form-check">
    <%= form.label :borrowed, class: 'form-check-label' %>
    <%= form.check_box :borrowed, class: 'form-check-input' %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :item_type, class: 'form-label' %>
    <%= form.select :item_type, Item.item_types.keys, { include_blank: 'Select item type....' }, class: 'form-select' %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>Name:</strong>
    <%= item.name %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= item.active %>
  </p>

  <p>
    <strong>Borrowed:</strong>
    <%= item.borrowed %>
  </p>

</div>

app/views/items/_items_list.html.erb
<div id="items" class="container-fluid">
  <table class="table">
    <thead>
    <tr>
      <th>Name</th>
      <th class="text-center">Active</th>
      <th class="text-center">Borrowed</th>
      <th class="text-center">Type</th>
      <% if action_name == 'borrowed' %>
        <th class="text-center">
          Borrowed to:
        </th>
      <% end %>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td class="text-center"><%= item.active ? '✅' : '❌' %></td>
        <td class="text-center"><%= item.borrowed ? '✅' : '❌' %></td>
        <td class="text-center"><%= item.item_type %></td>
        <% if action_name == 'borrowed' %>
          <td class="text-center">
            <%= item.borrowed_to.email %> <%= distance_of_time_in_words_to_now(item.borrowed_at) %>
            ago
          </td>
        <% end %>
        <td>
          <%= link_to "Show this item", item, class: 'btn btn-primary' %>
          <% if item.requested? %>
            <span class="badge badge-round-pill bg-success">
              Requests: <%= item.rental_requests.count %>
            </span>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/items/active.html.erb
<h1>Items active</h1>

<%= render 'items/items_list', items: @items %>

app/views/items/borrowed.html.erb
<h1>Items borrowed</h1>

<%= render 'items/items_list', items: @items %>

app/views/items/edit.html.erb
<div class="container-fluid">
  <h1>Editing items</h1>
  <%= render "form", item: @item %>
  <br>
  <%= link_to "Show this item", @item, class: 'btn btn-light min-width-btn' %> |
  <%= link_to "Back to items", items_path, class: 'btn btn-light min-width-btn' %>
</div>

app/views/items/inactive.html.erb
<h1>Items inactive</h1>

<%= render 'items/items_list', items: @items %>

app/views/items/index.html.erb
<p style="color: green;"><%= notice %></p>
<h1>Items</h1>
<%= link_to "New item", new_item_path, class: 'btn btn-primary' %>
<% if user_signed_in? %>
  <%= tag.span current_user.email %>
<% end %>

<%= render 'items/items_list', items: @items %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path, class: 'btn btn-light min-width-btn"' %>
</div>

app/views/items/on_place.html.erb
<h1>Items on place</h1>

<%= render 'items/items_list', items: @items %>

app/views/items/show.html.erb
<p style="color: green;"><%= notice %></p>
<div class="container-fluid">
  <h1>Item details</h1>
  <%= form_with(model: @item, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control", readonly: true %>
    </div>
    <div class="form-group form-check">
      <%= form.check_box :active, class: "form-check-input", disabled: true %>
      <%= form.label :active, class: "form-check-label" %>
    </div>
    <div class="form-group form-check">
      <%= form.check_box :borrowed, class: "form-check-input", disabled: true %>
      <%= form.label :borrowed, class: "form-check-label" %>
    </div>
    <div class="form-group mt-2 mb-2">
      <%= form.label :item_type %>
      <%= form.select :item_type, Item.item_types.keys, {}, class: 'form-select', disabled: true %>
    </div>
    <% if @item.borrowed && @item.borrowed_to %>
      <div class="d-flex flex-column">
        <p><%= @item.borrowed_to&.email %></p>
        <p><%= distance_of_time_in_words_to_now(@item.borrowed_at) %> ago</p>
      </div>
    <% end %>
  <% end %>
  <%= link_to 'Edit', edit_item_path(@item), class: "btn btn-primary min-width-btn" %>
  <%= link_to 'Back', items_path, class: "btn btn-light min-width-btn" %>
  <%= link_to 'Delete', item_path(@item), class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
  <% if @item.borrowed %>
    <%= link_to 'Return', return_item_item_path(@item), data: { turbo_method: :post } %>
  <% end %>

  <% if @item.requested? %>
    <hr/>
    <div class="d-flex flex-column">
      <% @item.rental_requests.each do |request| %>
        <div class="d-flex flex-row justify-content-between border-bottom">
          <div class="d-flex flex-column">
            <p><%= request.user.email %></p>
            <p><%= distance_of_time_in_words_to_now(request.created_at) %> ago</p>
          </div>
          <div>
            <%= link_to 'Accept', accept_rental_request_path(request), class: 'text-success', data: { turbo_method: :post, turbo_confirm: "Are you sure you want to borrow this item to #{request.user.email}?" } %>
            <%= link_to 'Reject', reject_rental_request_path(request), class: 'text-danger', data: { turbo_method: :post, turbo_confirm: 'Are you sure you want to reject this request?' } %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>